class MyException extends Exception {
    private String Teks;

    MyException(String s) {
        Teks = "Exeption generated by: " + s;
    }
}

class eksepsi {
    static void tampil(String s) throws MyException {
        System.out.println("tampil");
        if (s.equals("amir")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("ali");
            tampil("amir");
        } catch (MyException ex) {
            System.out.println("Tangkap:" + ex);
        }
    }
}